#!/usr/bin/env bash
set -euo pipefail

script_dir=$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)
repo_root=$(cd "$script_dir/../.." && pwd)
run_file_glob=("$repo_root"/research/runs/*.jsonl)
paper_dir="$script_dir"

die() {
    printf 'standard-to-grammar: %s\n' "$1" >&2
    exit 1
}

run_json() {
    local run_id=$1
    jq -s -c --arg run "$run_id" '
        [ .[] | select(.run == $run) ] as $matches
        | if ($matches | length) == 1 then $matches[0]
          else error("run is missing or duplicated: " + $run)
          end
    ' "${run_file_glob[@]}"
}

metric() {
    local run_id=$1
    local expression=$2
    run_json "$run_id" | jq -r "$expression"
}

assert_run() {
    local run_id=$1
    local expression=$2
    if ! run_json "$run_id" | jq -e "$expression" >/dev/null; then
        die "run assertion failed for $run_id: $expression"
    fi
}

while IFS= read -r run_id; do
    [[ -z "$run_id" || "$run_id" == \#* ]] && continue
    [[ "$run_id" =~ ^R[0-9]{6}$ ]] || die "invalid run ID: $run_id"
    run_json "$run_id" >/dev/null
done < "$paper_dir/runs.txt"

source_sha=$(awk -F'"' '/^sha256[[:space:]]*=/{print $2; exit}' \
    "$repo_root/artifacts/standards/j3-24-007.toml")
run_artifact=$(metric R000019 '.artifact')
run_source_sha=$(awk -F'"' '/^source_sha256[[:space:]]*=/{print $2; exit}' \
    "$repo_root/$run_artifact")
[[ "$source_sha" == "$run_source_sha" ]] || \
    die "selected run artifact source hash differs from the pinned source artifact"
[[ "$source_sha" == "$(awk -F'"' '/^source_sha256[[:space:]]*=/{print $2; exit}' \
    "$paper_dir/pins.toml")" ]] || die "paper source hash differs from source artifact"

assert_run R000017 '.status == "accepted" and .verification.zero_model_calls == true and .verification.scope_sets_equal == true and .verification.production_starts == 522'
assert_run R000019 '.status == "accepted" and .verification.zero_model_calls == true and .verification.syntax_objects == 522 and .verification.source_hash_on_every_record == true'
assert_run R000020 '.status == "accepted" and .verification.byte_identical == true'
for run_id in R000025 R000026 R000027 R000028; do
    assert_run "$run_id" '.status == "accepted" and .verification.zero_model_calls == true and .verification.syntax_records == 522 and .verification.production_order_difference == 0 or .verification.lhs_mapping_difference == 0'
done
assert_run R000029 '.status == "accepted" and .verification.independent_difference == 0'
assert_run R000030 '.status == "verification_failure" and .verification.antlr_unresolved_rule_names == 181 and .verification.bison_unresolved_symbol_names == 181'
assert_run R000031 '.status == "accepted" and .verification.unresolved_unique_names == 181 and .verification.unresolved_reference_occurrences == 472 and .verification.unresolved_referring_rules == 346'
assert_run R000050 '.status == "accepted" and .verification.cases_declared == 10 and .verification.all_three_agree_cases == 10 and .verification.disagreement_cases == 0'

document_pages=$(metric R000017 '.verification.pages')
core_pages=$(metric R000017 '.verification.core_pages')
production_starts=$(metric R000017 '.verification.production_starts')
scope_difference=$(metric R000017 '.verification.scope_sets_equal | if . then 0 else 1 end')
production_lines=$(metric R000017 '.verification.production_lines')
continuations=$(metric R000017 '.verification.production_continuations')
syntax_objects=$(metric R000019 '.verification.syntax_objects')
source_hash_records=$(metric R000019 '.verification.source_hash_on_every_record | if . then 522 else 0 end')
roundtrip=$(metric R000020 '.verification.byte_identical | if . then "byte-identical" else "different" end')
projection_count=4
unresolved_names=$(metric R000031 '.verification.unresolved_unique_names')
unresolved_occurrences=$(metric R000031 '.verification.unresolved_reference_occurrences')
unresolved_rules=$(metric R000031 '.verification.unresolved_referring_rules')

results="$paper_dir/results.md"
{
    cat <<EOF
# Generated results

Generated by \`papers/standard-to-grammar/analyse.sh\` from the run IDs in
\`papers/standard-to-grammar/runs.txt\`.

## Extraction and StandardIR

| Quantity | Value |
|---|---:|
| Indexed document pages | $document_pages |
| Selected syntax pages | $core_pages |
| Numbered production starts | $production_starts |
| Production lines | $production_lines |
| Continuation lines | $continuations |
| Full-document versus selected-scope difference | $scope_difference |
| StandardIR syntax objects | $syntax_objects |
| Records with source hash | $source_hash_records |
| StandardIR SX round-trip | $roundtrip |

## Grammar projections

The following rows are extracted from the accepted projection run records.

| Projection | Records | Provenance comments | Source-hash matches | Model calls |
|---|---:|---:|---:|---:|
EOF
    while IFS=: read -r run_id label; do
        printf '| %s | %s | %s | %s | %s |\n' \
            "$label" \
            "$(metric "$run_id" '.verification.syntax_records')" \
            "$(metric "$run_id" '.verification.provenance_comments')" \
            "$(metric "$run_id" '.verification.source_hash_matches')" \
            "$(metric "$run_id" '.verification.zero_model_calls | if . then 0 else "reported" end')"
    done <<'EOF'
R000025:EBNF
R000026:ANTLR4
R000027:Bison
R000028:tree-sitter
EOF
    cat <<EOF

## Comparison boundary

| Quantity | Value |
|---|---:|
| StandardIR unique rules in structural comparison | $(metric R000029 '.verification.standardir_unique_rules') |
| House grammar parser rules | $(metric R000029 '.verification.standard_parser_rules') |
| Kaby76 parser rules | $(metric R000029 '.verification.kaby76_parser_rules') |
| LFortran parser rules | $(metric R000029 '.verification.lfortran_parser_rules') |
| Flang rule IDs | $(metric R000029 '.verification.flang_rule_ids') |
| Unresolved names in target validation | $unresolved_names |
| Unresolved reference occurrences | $unresolved_occurrences |
| Referring rules | $unresolved_rules |
| Target-tool validation result | retained verification failure |

## External behavioral baseline

| Quantity | Value |
|---|---:|
| Fixed fixtures | $(metric R000050 '.verification.cases_declared') |
| Compiler invocations | $(metric R000050 '.verification.compiler_invocations') |
| Cases with agreement across LFortran, Flang, and gfortran | $(metric R000050 '.verification.all_three_agree_cases') |
| Cases with disagreement | $(metric R000050 '.verification.disagreement_cases') |

Every table in this file is regenerated by \`papers/standard-to-grammar/analyse.sh\`.
The underlying run records retain the independent oracles and the accepted
failure status.
EOF
} > "$results"

rendered=$(<"$paper_dir/manuscript.template.md")
rendered=${rendered//@PRODUCTION_STARTS@/$production_starts}
rendered=${rendered//@CORE_PAGES@/$core_pages}
rendered=${rendered//@DOCUMENT_PAGES@/$document_pages}
rendered=${rendered//@PROJECTION_COUNT@/$projection_count}
rendered=${rendered//@UNRESOLVED_NAMES@/$unresolved_names}
rendered=${rendered//@UNRESOLVED_OCCURRENCES@/$unresolved_occurrences}
rendered=${rendered//@UNRESOLVED_RULES@/$unresolved_rules}
{
    printf '%s\n\n' "$rendered"
    cat "$results"
} > "$paper_dir/paper.md"

printf 'standard-to-grammar: regenerated results.md and paper.md\n'
