#!/usr/bin/env bash
# Regenerate research/index.md from manifests and run records.
#
# The index is generated, never edited. If a number in it is wrong, the fix
# belongs in the data or in this script. That rule is the whole reason the file
# exists: LESSONS.md section 7 documents what typed-in status numbers do.

source "$(dirname "${BASH_SOURCE[0]}")/lib.sh"

EXP="$ROOT/research/experiments"
RUNS="$ROOT/research/runs"
OUT="$ROOT/research/index.md"

runs_all() { cat "$RUNS"/*.jsonl 2>/dev/null || true; }

count_field() {   # count_field FIELD VALUE
    runs_all | grep -c "\"$1\":\"$2\"" || true
}

{
    printf '# Research index\n\n'
    printf 'Generated by `scripts/index.sh` on %s. Do not edit.\n\n' "$(date -u +%Y-%m-%d)"

    total=$(runs_all | grep -c . || true)
    printf 'Runs recorded: %s\n\n' "${total:-0}"

    printf '## Experiments\n\n'
    printf '| ID | Status | Runs | Question |\n|---|---|---|---|\n'
    found=0
    for d in "$EXP"/E[0-9][0-9][0-9][0-9]-*/; do
        [ -d "$d" ] || continue
        found=1
        id=$(basename "$d" | cut -d- -f1)
        status=$(awk -F": *" "/^status:/{sub(/ *#.*/, \"\", \$2); print \$2; exit}" "$d/manifest.yaml" 2>/dev/null)
        question=$(awk '/^question:/{getline; sub(/^[ \t]*/,""); print; exit}' \
                   "$d/manifest.yaml" 2>/dev/null)
        n=$(count_field experiment "$id")
        printf '| %s | %s | %s | %s |\n' "$id" "${status:-?}" "$n" "${question:-?}"
    done
    [ "$found" = 1 ] || printf '| _none yet_ | | | |\n'

    printf '\n## Run status\n\n'
    printf '| Status | Count |\n|---|---|\n'
    any=0
    for s in accepted parse_failure type_failure semantic_failure \
             verification_failure mutation_failure performance_rejected \
             timeout compiler_crash model_error abandoned; do
        n=$(count_field status "$s")
        [ "${n:-0}" -gt 0 ] || continue
        any=1
        printf '| %s | %s |\n' "$s" "$n"
    done
    [ "$any" = 1 ] || printf '| _no runs yet_ | |\n'

    printf '\n## Artifact origin\n\n'
    printf '| Origin | Count |\n|---|---|\n'
    any=0
    for o in MECHANICAL SEARCH SMT LLM LLM_REPAIR HUMAN IMPORTED DIFFERENTIAL; do
        n=$(count_field origin "$o")
        [ "${n:-0}" -gt 0 ] || continue
        any=1
        printf '| %s | %s |\n' "$o" "$n"
    done
    [ "$any" = 1 ] || printf '| _no artifacts yet_ | |\n'

    printf '\n## Decisions\n\n'
    printf '| ID | Status | Relation | Title |\n|---|---|---|---|\n'
    found=0
    for f in "$ROOT"/research/decisions/D[0-9][0-9][0-9][0-9]-*.md; do
        [ -f "$f" ] || continue
        found=1
        id=$(basename "$f" | cut -d- -f1)
        title=$(sed -n '1s/^# D[0-9]*\.\? *//p' "$f")
        status=$(awk -F': *' '/^Status:/{print $2; exit}' "$f")
        rel=$(awk -F': *' '/^(Supersedes|Amends|Retracts):/{printf "%s %s; ", $1, $2}' "$f")
        printf '| [%s](decisions/%s) | %s | %s | %s |\n' \
            "$id" "$(basename "$f")" "${status:-?}" "${rel%; }" "${title:-?}"
    done
    [ "$found" = 1 ] || printf '| _none yet_ | | | |\n'

    printf '\n### Proposed decisions\n\n'
    printf '| ID | Title | File |\n|---|---|---|\n'
    found=0
    for f in "$ROOT"/research/decisions/D[0-9][0-9][0-9][0-9]-*.md; do
        [ -f "$f" ] || continue
        status=$(awk -F': *' '/^Status:/{print $2; exit}' "$f")
        [ "$status" = proposed ] || continue
        found=1
        id=$(basename "$f" | cut -d- -f1)
        title=$(sed -n '1s/^# D[0-9]*\.\? *//p' "$f")
        printf '| [%s](decisions/%s) | %s | `%s` |\n' \
            "$id" "$(basename "$f")" "${title:-?}" "$(basename "$f")"
    done
    [ "$found" = 1 ] || printf '| _none_ | | |\n'

    printf '\n## Pinned artifacts\n\n'
    printf '| Name | Bytes | Licence | Purpose |\n|---|---|---|---|\n'
    while read -r m; do
        [ -n "$m" ] || continue
        printf '| %s | %s | %s | %s |\n' \
            "$(toml_get "$m" name)" "$(toml_get "$m" bytes)" \
            "$(toml_get "$m" licence)" "$(toml_get "$m" purpose)"
    done < <(find "$ROOT/artifacts" -name '*.toml' | sort)
} > "$OUT"

note "wrote $OUT"
